Rocky/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;
using Rocky.Repository.IRepository;

namespace Rocky.Controllers;

public class ApplicationTypeController:Controller
{
    private readonly IApplicationTypeRepository _db;

    public ApplicationTypeController(IApplicationTypeRepository db)
    {
        _db = db;
    }
    // GET
    public IActionResult Index()
    {
        IEnumerable<ApplicationType> objList = _db.GetAll();
        return View(objList);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(ApplicationType obj)
    {
        _db.Add(obj);
        _db.Save();
        return RedirectToAction("Index");
    }
    
    
    public IActionResult Edit(int? id)
    {
        if (id == null || id==0)
        {
            return NotFound();
        }
        var obj = _db.Find(id.GetValueOrDefault());
        return View(obj);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(ApplicationType obj)
    {
        if (ModelState.IsValid)
        {
            _db.Update(obj);
            _db.Save();
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id==0)
        {
            return NotFound();
        }
        var obj = _db.Find(id.GetValueOrDefault());
        return View(obj);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var obj = _db.Find(id.GetValueOrDefault());
        _db.Remove(obj); 
        _db.Save();
        return RedirectToAction("Index");
    }

}

Rocky/Views/ApplicationType/Create.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ApplicationType

@{
    ViewBag.Title = "Create Application";
    Layout = "_Layout";
}


<form method="post" asp-action="Create">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="p-3 border">
        <div class="form-group row">
            <h2 class="text-info pl-3"> Add Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                    </div>

                </div>
                <br/>
                @* <div class="form-group row"> *@
                @*     <div class="col-4"> *@
                @*         <label asp-for="DisplayOrder"></label> *@
                @*     </div> *@
                @*     <div class="col-8"> *@
                @*         <input asp-for="DisplayOrder" class="form-control" /> *@
                @*     </div> *@
                @* *@
                @* </div> *@
                <br/>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" width="100%" value="Create"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100" width="100%"> Break</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>


@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Rocky/Views/ApplicationType/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ApplicationType

@{
    ViewBag.Title = "Delete";
    Layout = "_Layout";
}
<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="p-3 border">
        <div class="form-group row">
            <h2 class="text-info pl-3"> Delete Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled="disabled" class="form-control"/>
                    </div>

                </div>
                <br/>
           
                <br/>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" width="100%" value="Delete"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100" width="100%"> <i class="fas fa-sign-out"></i> &nbsp;</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Rocky/Views/ApplicationType/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ApplicationType

@{
    ViewBag.Title = "Edit Application Type";
    Layout = "_Layout";
}
<form method="post">
    <input asp-for="Id" hidden/>
    <div class="p-3 border">
        <div class="form-group row">
            <h2 class="text-info pl-3"> Edit Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                    </div>

                </div>
                <br/>
                <br/>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" width="100%" value="Update"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100" width="100%"> <i class="fas fa-sign-out"></i> &nbsp;</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Rocky/Views/ApplicationType/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<ApplicationType>

@{
    ViewBag.Title = "Category";
    Layout = "_Layout";
}

<div class="container p-3">
    <div class="row pt-4 ">
        <div class="col-6">
            <h2 class="text-primary">Application Type</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Create" class="text-white btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp;
                Create New Application Type
            </a>
        </div>
    </div>
    <br/><br/>
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width: 100%">
            <thead>
            <tr>
                <th>
                    Application Type
                </th>
                <th class="text-center">
                    Change ?
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%" >@obj.Name</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ApplicationType" 
                               asp-route-id="@obj.Id" asp-action="Edit"
                               class="btn btn-primary mx-2" > <i class="fas fa-edit"></i>
                                &nbsp;</a>
                            <a asp-controller="ApplicationType" asp-route-id="@obj.Id"
                               asp-action="Delete" class="btn btn-danger mx-2"><i class="far fa-trash-alt "></i> &nbsp;</a>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <h3>No Application Yet</h3>
    }
</div>