Rocky/Controllers/CartController.cs
using System.Security.Claims;
using System.Text;
using Braintree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_Utility;
using Rocky.Data;
using Rocky.Models;
using Rocky.Models.ViewModel;
using Rocky.Repository.IRepository;
using Rocky.Utility;

namespace Rocky.Controllers;

[Authorize]
public class CartController : Controller
{
    private readonly IApplicationUserRepository _userRepo;
    private readonly IProductRepository _productRepository;
    private readonly IInquiryDetailRepository _detailRepository;
    private readonly IInquiryHeaderRepository _headerRepository;
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly IOrderDetailsRepository _orderDetails;
    private readonly IOrderHeaderRepository _orderHeader;
    private readonly IBrainTreeGate _brainTree;
    
    
    [BindProperty]
    public ProductUserVm ProductUserVm { get; set; }

    public CartController(
        IOrderDetailsRepository orderDetails,
        IOrderHeaderRepository orderHeader,
        IWebHostEnvironment webHostEnvironment,
        IInquiryDetailRepository detailRepository, 
        IApplicationUserRepository userRepo,
        IInquiryHeaderRepository headerRepository,
        IProductRepository productRepository,
        IBrainTreeGate brainTree
        )
    {
        _detailRepository = detailRepository;
        _headerRepository = headerRepository;
        _productRepository = productRepository;
        _userRepo = userRepo;
        _webHostEnvironment = webHostEnvironment;
        _orderDetails=orderDetails;
        _orderHeader=orderHeader;
        _brainTree = brainTree;
    }
    // GET
    public IActionResult Index()
    {
        List<ShoppingCart> shoppingCartsLIst = new List<ShoppingCart>();
        if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null &&
            HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0
           )
        {
            shoppingCartsLIst=HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }

        List<int> prodInCart = shoppingCartsLIst.Select(i => i.ProductId).ToList();
        IEnumerable<Product> productsTempList = _productRepository.GetAll(u => prodInCart.Contains(u.Id));
        List<Product> prodList = new List<Product>();
        foreach (var cartObj in shoppingCartsLIst)
        {
            Product prodTemp = productsTempList.FirstOrDefault(u => u.Id == cartObj.ProductId);
            prodTemp.TempSqFt = cartObj.SqFt;
            prodList.Add(prodTemp);
        }
        return View(prodList);
    }

    public IActionResult Remove(int id)
    {
        List<ShoppingCart> shoppingCartsLIst = new List<ShoppingCart>();
        if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null &&
            HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0
           )
        {
            shoppingCartsLIst=HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }
        shoppingCartsLIst.Remove(shoppingCartsLIst.FirstOrDefault(u=>u.ProductId == id));
        HttpContext.Session.Set(WC.SessionCart,shoppingCartsLIst);
        return RedirectToAction(nameof(Index));

    }
    
    [ValidateAntiForgeryToken] 
    [HttpPost,ActionName("Index")]
    public IActionResult IndexPost(IEnumerable<Product> prodList)
    {
        List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
        foreach (var product in prodList)
        {
            shoppingCartList.Add(new ShoppingCart{ ProductId = product.Id,SqFt = product.TempSqFt});
        }
        HttpContext.Session.Set(WC.SessionCart,shoppingCartList);
        return RedirectToAction(nameof(Summary));
    }

    public IActionResult Summary()
    {
        ApplicationUser applicationUser;
        if (User.IsInRole(WC.AdminRole))
        {
            if (HttpContext.Session.Get<int>(WC.SessionInquiryId) != 0)
            {
                InquiryHeader inquiryHeader = _headerRepository.FirstOrDefault(u =>
                    u.Id == HttpContext.Session.Get<int>(WC.SessionInquiryId));
                applicationUser = new ApplicationUser()
                {
                    Email = inquiryHeader.Email,
                    Fullname = inquiryHeader.FullName,
                    PhoneNumber = inquiryHeader.PhoneNumber
                };
            }
            else
            {
                applicationUser = new ApplicationUser();
            }

            var brain = _brainTree.GetGateWay();
            var clientToken = brain.ClientToken.Generate();
            ViewBag.ClientToken = clientToken;
        }
        else
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims =claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            applicationUser = _userRepo.FirstOrDefault(u => u.Id == claims.Value);
        }
        List<ShoppingCart> shoppingCartsLIst = new List<ShoppingCart>();
        if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null &&
            HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
        {
            shoppingCartsLIst=HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
        }

        List<int> prodInCart = shoppingCartsLIst.Select(i => i.ProductId).ToList();
        List<Product> productsList = _productRepository.GetAll(u => prodInCart.Contains(u.Id)).ToList();
        ProductUserVm = new ProductUserVm()
        {
            ApplicationUser = applicationUser,
         };

        foreach (var cart in shoppingCartsLIst)
        {
            Product prodTemp = _productRepository.FirstOrDefault(u=> u.Id == cart.ProductId);
            prodTemp.TempSqFt = cart.SqFt;
            ProductUserVm.ProductList.Add(prodTemp);
        }
        return View(ProductUserVm);

    }
    
    [HttpPost,ActionName("Summary")]
    public IActionResult SummaryPost(IFormCollection collection,ProductUserVm productUserVm )
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        if (User.IsInRole(WC.AdminRole))
        {
            var orderTotal = 0.0;
            foreach (var product in ProductUserVm.ProductList)
            {
                orderTotal += product.Price * product.TempSqFt;
            }
            
            OrderHeader orderHeader = new OrderHeader()
            {
                CreatedByUserId = claim.Value,
                FinalOrderTotal = orderTotal,
                City = ProductUserVm.ApplicationUser.City,
                Email = ProductUserVm.ApplicationUser.Email,
                StreetAddress = ProductUserVm.ApplicationUser.StreetAddress,
                State = ProductUserVm.ApplicationUser.State,
                PostalCode = ProductUserVm.ApplicationUser.PostalCode,
                FullName = ProductUserVm.ApplicationUser.Fullname,
                PhoneNumber= ProductUserVm.ApplicationUser.PhoneNumber,
                OrderDate = DateTime.Now,
                OrderStatus = WC.StatusPending,
                TransactionId = "id_place_holder"
            };
            _orderHeader.Add(orderHeader);
            _orderHeader.Save();
            
            foreach (var prod in ProductUserVm.ProductList)
            {
                OrderDetails orderDetails = new OrderDetails()
                {
                    OrderHeaderId = orderHeader.Id,
                    PricePerSqFt = prod.Price,
                    Sqft = prod.TempSqFt,
                    ProductId = prod.Id,
                };
                _orderDetails.Add(orderDetails);
            }
            _orderDetails.Save();
            string nonceFromClient = collection["payment_method_nonce"];
            var request = new TransactionRequest
            {
                Amount = Convert.ToDecimal(orderHeader.FinalOrderTotal),
                PaymentMethodNonce = nonceFromClient,
                OrderId = orderHeader.Id.ToString(),
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                }
             };
             var gateway = _brainTree.GetGateWay();
             Result<Transaction> result = gateway.Transaction.Sale(request);
            
             if (result.Target.ProcessorResponseText == "Approved")
             {
                 orderHeader.TransactionId = result.Target.Id;
                 orderHeader.OrderStatus = WC.StatusApproved;
             }
             else
             {
                 orderHeader.OrderStatus = WC.StatusCancel;
             }
             _orderHeader.Save();
            return RedirectToAction(nameof(InquiryConfirmation), new {id=orderHeader.Id});
        }
        else
        {
            var PathToTemplates = _webHostEnvironment.WebRootPath
                                  + Path.DirectorySeparatorChar.ToString()
                                  + "templates" + Path.DirectorySeparatorChar.ToString() 
                                  + "Inquiry.html";
            string HtmlBody = "";
            using (StreamReader sr = System.IO.File.OpenText(PathToTemplates))
            {
                HtmlBody = sr.ReadToEnd();
            }

            StringBuilder productListSB = new StringBuilder();
            foreach (var prod in ProductUserVm.ProductList)
            {
                productListSB.Append($" - Name: {prod.Name} <span style='font-size:14px;'> (ID: {prod.Id})</span> <br/> ");
            }

            string messageBody = string.Format(HtmlBody,
                ProductUserVm.ApplicationUser.Fullname,
                ProductUserVm.ApplicationUser.Email,
                ProductUserVm.ApplicationUser.PhoneNumber,
                productListSB.ToString()
            );
            //SEND EMAIL CODE (Message body is already defined ))

Rocky/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky_Utility;
using Rocky.Data;
using Rocky.Models;
using Rocky.Repository.IRepository;

namespace Rocky.Controllers;

public class CategoryController : Controller
{
    private readonly ICategoryRepository _db;

    public CategoryController(ICategoryRepository db)
    {
        _db = db;
    }
    public IActionResult Index()
    {
        IEnumerable<Category> objList = _db.GetAll();
        return View(objList);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Category obj)
    {
        if (ModelState.IsValid)
        {
            _db.Add(obj);
            _db.Save();
            TempData[WC.Success] = "Category Created Succeessful";
            return RedirectToAction("Index");
        }

        TempData[WC.Error] = "Eroor WHile Creating Category";

        return View(obj);
    }

    public IActionResult Edit(int? id)
    {
        if (id == null || id==0)
        {
            return NotFound();
        }
        var obj = _db.Find(id.GetValueOrDefault());
        return View(obj);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Category obj)
    {
        if (ModelState.IsValid)
        {
            _db.Update(obj);
            _db.Save();
            return RedirectToAction("Index");
        }
        return View(obj);
    }

    public IActionResult Delete(int? id)
    {
        if (id == null || id==0)
        {
            return NotFound();
        }
        var obj = _db.Find(id.GetValueOrDefault());
        return View(obj);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var obj = _db.Find(id.GetValueOrDefault());
        _db.Remove(obj); 
        _db.Save();
        return RedirectToAction("Index");
    }
}

Rocky/Controllers/ProductController.cs
using System.Collections;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rocky_Utility;
using Rocky.Data;
using Rocky.Models;
using Rocky.Models.ViewModel;
using Rocky.Repository.IRepository;

namespace Rocky.Controllers;

[Authorize(Roles = WC.AdminRole)]
public class ProductController : Controller
{
    private readonly IProductRepository _db;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public ProductController(IProductRepository db,IWebHostEnvironment webHostEnvironment)
    {
        _db = db;
        _webHostEnvironment = webHostEnvironment;
    }
    public IActionResult Index()
    {
        IEnumerable<Product> objList = _db.GetAll(includeProperties:"Category,ApplicationType"); 
        return View(objList);
    }
    public IActionResult Upsert(int? id)
    {
        var productVm = new ProductVM()
        {
            CategorySelectList =_db.getAllDropDownCategories(),
            ApplicationTypes = _db.getAllDropDownApplicationTypes(),
            Product = new Product(),
        };
        if (id ==null)
        {
            return View(productVm);
        }
        else
        {
            productVm.Product = _db.Find(id.GetValueOrDefault());
            if (productVm.Product == null)
            {
                return NotFound();
            }
            return View(productVm);
        }
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductVM obj)
    {
  
            var files = HttpContext.Request.Form.Files;
            string webrootPath = _webHostEnvironment.WebRootPath;

            if (obj.Product.Id == 0)
            {
                string upload = webrootPath + WC.ImagePath;
                string fileName = Guid.NewGuid().ToString();
                string extension = Path.GetExtension(files[0].FileName);

                using (var fileStream= new FileStream(Path.Combine(upload,fileName+extension),FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                obj.Product.Image = fileName + extension;
                _db.Add(obj.Product);
            }
            else
            {
                var objFromDb = _db.FirstOrDefault(c => obj.Product.Id == c.Id,isTracking:false);
                if (files.Count > 0)    
                {
                    string upload = webrootPath + WC.ImagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);

                    var oldFile = Path.Combine(upload, objFromDb.Image);
                    if (System.IO.File.Exists(oldFile))
                    {
                        System.IO.File.Delete(oldFile);
                    }
                    using (var fileStream= new FileStream(Path.Combine(upload,fileName+extension),FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }   
                    obj.Product.Image = fileName + extension;

                }
                else
                {
                    obj.Product.Image = objFromDb.Image;
                }

                _db.Update(obj.Product);

            }
            _db.Save();
            return RedirectToAction("Index");
      

        return View(obj);
    }
    
    public IActionResult Delete(int id)
    {
        if (id == null || id==0)
        {
            return NotFound();
        }

        var obj = _db.FirstOrDefault(u => u.Id == id, includeProperties: "Category,ApplicationType");
        if(obj==null)
        {
            return NotFound();
        }
        return View(obj);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var obj = _db.Find(id.GetValueOrDefault());
        if (obj == null)
        {
            return NotFound();
        }
        string upload = _webHostEnvironment.WebRootPath + WC.ImagePath;

        var oldFile = Path.Combine(upload, obj.Image);
        if (System.IO.File.Exists(oldFile))
        {
            System.IO.File.Delete(oldFile);
        }
        
        _db.Remove(obj); 
        _db.Save();
        return RedirectToAction("Index");
    }
}

Rocky/Views/Shared/_IndividualProductCard.cshtml
@using Rocky_Utility
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Product

<div class="col-lg-4 col-md-6 pb-4  filter @Model.Category.Name.Replace(' ','_')">
    <!-- Card-->
    <div class="card bg-warning rounded shadow-bg" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}",Model.Price)</span> / Kg</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ImagePath/@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100" style="background-color:lavenderblush; color: black">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100" style="background-color:aliceblue; color: black">@Model.ApplicationType.Name</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify" >
                <p> @Model.ShortDesc</p>
            </div>
            <div class="col-12 p-1">
                <a class="btn btn-danger form-control btn-sm p-2" asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

Rocky/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Rocky_Utility
@using Rocky.Utility
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Rocky</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Rocky.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" 
         href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
     <!-- Syncfusion ASP.NET Core controls styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.2.43/fluent.css" />
        <!-- Syncfusion ASP.NET Core controls scripts -->
    <script src="https://cdn.syncfusion.com/ej2/20.2.43/dist/ej2.min.js"></script>
    


</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-danger border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-th-large"></i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex ">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                           Home                  
                            </a>
                    </li>
                    @if (User.IsInRole(WC.AdminRole))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="NavBarDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Content Management</a>
                            <div class="dropdown-menu" aria-labelledby="NavBarDropDown">
                                <a class="nav-link text-dark" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                                <a class="nav-link text-dark" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Product</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </div>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="NavBarDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Order/Inquiry Management</a>
                            <div class="dropdown-menu" aria-labelledby="NavBarDropDown">
                                <a class="nav-link text-dark" asp-controller=Inquiry asp-action="Index">Inquiry</a>
                                <a class="nav-link text-dark" asp-controller=Order asp-action="Index">Order</a>
                                </div>
                        </li>
                    }
                    <li>
                        @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) != null)
                        {
                            <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                @{
                                    var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;
                                }
                                <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                            </a>
                        }
                        else
                        {
                            <a href="#" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp;(0)
                            </a>
                        }
                    </li>
                </ul>
                               <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>

<footer class="border-top footer bg-danger">
    <div class="container text-white-50">
        &copy; 2022 - Rocky - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.all.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>



<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
<ejs-scripts></ejs-scripts>
</body>
</html>

Rocky/Views/Shared/_Notification.cshtml
@using Rocky_Utility
@if (TempData[WC.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"> </script>
    <script type="text/javascript">
            toastr.success('@TempData[WC.Success]') 
    </script>
}

@if (TempData[WC.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"> </script>
    <script type="text/javascript">
            toast.error('@TempData[WC.Success]') 
    </script>
}